name: Build & Test

on:
  push:
    branches:
      - badges

jobs:
  build:
    name: Build and Test
    runs-on: macOS-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
            
    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install SPM Dependencies
      run: swift build

    - name: Build and Test
      run: |
        xcodebuild test 
          -project Cocktails.xcodeproj \
          -scheme CocktailsTests \
          -destination "platform=iOS Simulator,name=iPhone 11" \
            clean test | xcpretty
